name: 'Claude Code Action'
description: 'Run Claude Code CLI to perform automated code tasks based on natural language prompts'
author: 'cielo-red'
branding:
  icon: 'code'
  color: 'purple'

inputs:
  prompt:
    description: 'The natural language prompt describing what Claude Code should do'
    required: false
    default: ''
  
  # Authentication
  anthropic_api_key:
    description: 'Anthropic API key for Claude Code authentication'
    required: false
  claude_credentials:
    description: 'Claude CLI credentials JSON (base64 encoded)'
    required: false
  
  # Optional configuration
  auto_approve:
    description: 'Automatically approve Claude Code actions without prompts'
    required: false
    default: 'true'
  additional_args:
    description: 'Additional command line arguments to pass to Claude Code'
    required: false
    default: ''

outputs:
  execution_output:
    description: 'The output from Claude Code execution'
    value: ${{ steps.run-claude-code.outputs.execution_output }}
  files_changed:
    description: 'List of files modified by Claude Code'
    value: ${{ steps.run-claude-code.outputs.files_changed }}
  status:
    description: 'Execution status (success/failure)'
    value: ${{ steps.run-claude-code.outputs.status }}

runs:
  using: 'composite'
  steps:
    - name: Setup Claude credentials
      if: inputs.claude_credentials != ''
      shell: bash
      run: |
        mkdir -p ~/.claude
        echo "${{ inputs.claude_credentials }}" | base64 -d > ~/.claude/.credentials.json
    
    - name: Run Claude Code
      id: run-claude-code
      uses: anthropics/claude-code-action@v1
      with:
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        prompt: ${{ inputs.prompt }}
        claude_args: ${{ inputs.auto_approve == 'true' && format('--yes {0}', inputs.additional_args) || inputs.additional_args }}