name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating branches and commits
      pull-requests: write  # Required for creating PRs
      issues: write  # Required for commenting on issues
      id-token: write  # Required for OIDC authentication
      actions: read  # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: cielo-red/agent@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Extract prompt from the triggering comment/issue
          prompt: |
            ${{ github.event_name == 'issue_comment' && github.event.comment.body ||
                github.event_name == 'pull_request_review_comment' && github.event.comment.body ||
                github.event_name == 'pull_request_review' && github.event.review.body ||
                github.event_name == 'issues' && github.event.issue.body ||
                'Please assist with this task' }}

          # Model configuration
          model: claude-3-5-sonnet-20241022
          temperature: 0
          max_tokens: 8192

          # Behavior
          auto_approve: true
          create_pr: false  # Don't create PR when responding to comments

          # Optional: Add cielo_args to customize behavior
          # cielo_args: '--allowed-tools "Bash(gh pr:*)"'

