name: Cielo Red Example

on:
  # Trigger on issue comments
  issue_comment:
    types: [created]
  
  # Trigger on pull request comments
  pull_request_review_comment:
    types: [created]
  
  # Trigger on new issues
  issues:
    types: [opened, assigned]
  
  # Manual trigger
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Task for Cielo Red to perform'
        required: true
        type: string

jobs:
  cielo-red:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      id-token: write
    # Only run if comment contains @cielo-red or issue is assigned to cielo-red[bot]
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@cielo-red')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@cielo-red')) ||
      (github.event_name == 'issues' && github.event.assignee.login == 'cielo-red[bot]') ||
      github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run Cielo Red
        id: run-cielo-red
        uses: cielo-red/agent@v1.2.3
        with:
          # Authentication - use claude_credentials (recommended) or anthropic_api_key
          claude_credentials: ${{ secrets.CLAUDE_CREDENTIALS }}
          
          # Prompt configuration
          prompt: |
            ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.prompt || 
               github.event_name == 'issue_comment' && github.event.comment.body ||
               github.event_name == 'pull_request_review_comment' && github.event.comment.body ||
               github.event_name == 'issues' && github.event.issue.body || 
               'Review and provide feedback' }}
          
          # Configuration
          auto_approve: false
      
      - name: Comment on Issue/PR
        if: success() && (github.event_name == 'issue_comment' || github.event_name == 'issues')
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const prUrl = '${{ steps.run-cielo-red.outputs.pr_url }}';
            const filesChanged = '${{ steps.run-cielo-red.outputs.files_changed }}';
            const executionOutput = `${{ steps.run-cielo-red.outputs.execution_output }}`;
            
            let comment = '## 🤖 Claude Code Response\n\n';
            
            // Add the actual Claude Code output
            if (executionOutput) {
              comment += '### Output\n';
              comment += '```\n';
              comment += executionOutput.substring(0, 3000); // Limit for comment size
              if (executionOutput.length > 3000) {
                comment += '\n... (truncated for brevity)\n';
              }
              comment += '\n```\n\n';
            }
            
            // Add PR and files info if available
            if (prUrl) {
              comment += `📝 **Pull Request:** ${prUrl}\n`;
            }
            
            if (filesChanged) {
              comment += `📄 **Files modified:** ${filesChanged}\n`;
            }
            
            if (!executionOutput && !prUrl && !filesChanged) {
              comment += '✅ Task completed with no output or changes.\n';
            }
            
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: comment
            });

# Example usage scenarios:

# 1. Issue Comment Trigger:
#    Comment "@cielo-red please fix the typos in README.md"

# 2. Issue Assignment:
#    Assign an issue to cielo-red[bot] user

# 3. Manual Workflow Dispatch:
#    Go to Actions tab → Select workflow → Run workflow → Enter prompt

# 4. Pull Request Review:
#    Comment "@cielo-red review this code for security issues"